"""Flat, orthogonal evaluator for architecture-level QAS."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

import numpy as np

from ...channel.backends.base import Backend
from ...channel.noise.model import NoiseModel
from ._types import ArchitectureScore, ArchitectureSpec, MetricDefinition, MetricGroupScore
from ._utils import assign_ranks, clipped_score, ensure_backend
from .metrics_expressibility import KL_Haar_divergence, MMD_relative
from .metrics_hardware import native_depth_twoq_efficiency, native_depth_twoq_efficiency_details
from .metrics_noise import ion_trap_error_budget_proxy
from .metrics_trainability import structure_proxy, structure_proxy_details
from .reward import RewardComposer, RewardWeights


def metric_catalog(active_metrics: Optional[Dict[str, str]] = None) -> Dict[str, List[MetricDefinition]]:
    active_metrics = active_metrics or {}
    catalog = {
        "expressibility": [
            MetricDefinition("kl_haar", "KL divergence from the Haar fidelity distribution", "implemented"),
            MetricDefinition("mmd_relative", "MMD distance to Haar-like samples", "implemented"),
            MetricDefinition("frame_potential", "Distance from unitary/state design behavior", "todo"),
            MetricDefinition("entangling_capability", "Average entanglement generated by sampled parameters", "todo"),
            MetricDefinition("transformer_predictor", "Learned surrogate for expressibility", "todo"),
        ],
        "trainability": [
            MetricDefinition("structure_proxy", "Depth, two-qubit density, and parameter-count heuristic", "implemented"),
            MetricDefinition("gradient_variance", "Sampled parameter-gradient variance", "todo"),
            MetricDefinition("gradient_norm", "Sampled gradient norm statistics", "todo"),
            MetricDefinition("barren_plateau_risk", "Risk estimate from expressibility, depth, and noise", "todo"),
        ],
        "noise_robustness": [
            MetricDefinition("ion_trap_error_budget_proxy", "Ion-trap error budget from the default noise configuration", "implemented"),
            MetricDefinition("ideal_noisy_score_gap", "Direct ideal-vs-noisy score gap", "todo"),
            MetricDefinition("noise_sensitivity", "Gate-type sensitivity under a NoiseModel", "todo"),
            MetricDefinition("per_source_ablation", "Noise-source ablation such as idle/crosstalk/twoq", "todo"),
        ],
        "hardware_efficiency": [
            MetricDefinition("native_depth_twoq_efficiency", "Native-gate, depth, and two-qubit-count heuristic", "implemented"),
            MetricDefinition("connectivity_penalty", "Penalty from non-native connectivity or routing cost", "todo"),
            MetricDefinition("calibrated_error_cost", "Hardware-calibrated error/resource cost", "todo"),
            MetricDefinition("latency_cost", "Gate-time or schedule-length cost", "todo"),
        ],
    }
    defaults = {
        "expressibility": "kl_haar",
        "trainability": "structure_proxy",
        "noise_robustness": "ion_trap_error_budget_proxy",
        "hardware_efficiency": "native_depth_twoq_efficiency",
    }
    for group_name, metrics in catalog.items():
        active_name = active_metrics.get(group_name, defaults[group_name])
        for metric in metrics:
            metric.active = metric.name == active_name
    return catalog


class ArchitectureEvaluator:
    """Evaluate candidates with one active metric per orthogonal objective group."""

    def __init__(
        self,
        backend: Optional[Backend] = None,
        noise_model: Optional[NoiseModel] = None,
        weights: Optional[RewardWeights] = None,
        n_samples: int = 200,
        active_metrics: Optional[Dict[str, str]] = None,
    ):
        self.backend = backend
        self.noise_model = noise_model
        self.weights = weights or RewardWeights()
        self.reward_composer = RewardComposer(self.weights)
        self.n_samples = int(n_samples)
        self.active_metrics = active_metrics or {}

    def _active_metric_name(self, group_name: str) -> str:
        catalog = metric_catalog(self.active_metrics)
        return next(metric.name for metric in catalog[group_name] if metric.active)

    def _group_score(
        self,
        group_name: str,
        score: float,
        raw_values: Optional[Dict[str, Any]] = None,
        notes: Optional[List[str]] = None,
    ) -> MetricGroupScore:
        catalog = metric_catalog(self.active_metrics)
        active = next(metric.name for metric in catalog[group_name] if metric.active)
        return MetricGroupScore(
            name=group_name,
            active_metric=active,
            metrics=catalog[group_name],
            score=clipped_score(score),
            raw_values=raw_values or {},
            notes=notes or [],
        )

    def _evaluate_expressibility(self, architecture: ArchitectureSpec, backend: Backend) -> MetricGroupScore:
        metric_name = self._active_metric_name("expressibility")
        if metric_name == "kl_haar":
            try:
                distance = KL_Haar_divergence(architecture.circuit, samples=self.n_samples, backend=backend)
                score = float(np.exp(-distance))
            except Exception:
                score = structure_proxy(architecture.circuit)
                return self._group_score("expressibility", score, {"fallback_score": score}, ["Fell back to structural proxy."])
            return self._group_score("expressibility", score, {"kl_haar_score": score})
        if metric_name == "mmd_relative":
            score = MMD_relative(architecture.circuit, samples=self.n_samples, backend=backend)
            return self._group_score("expressibility", score, {"mmd_relative_score": score})
        raise NotImplementedError(f"Unsupported expressibility metric: {metric_name}")

    def evaluate(self, architecture: ArchitectureSpec) -> ArchitectureScore:
        backend = ensure_backend(self.backend)
        self.backend = backend
        circuit = architecture.circuit

        expressibility = self._evaluate_expressibility(architecture, backend)
        train_score = structure_proxy(circuit)
        trainability = self._group_score("trainability", train_score, structure_proxy_details(circuit))
        noise_score, noise_raw_values = ion_trap_error_budget_proxy(circuit)
        noise_robustness = self._group_score(
            "noise_robustness",
            noise_score,
            {"ion_trap_error_budget_proxy_score": noise_score, **noise_raw_values},
        )
        hardware_score = native_depth_twoq_efficiency(circuit)
        hardware_efficiency = self._group_score(
            "hardware_efficiency",
            hardware_score,
            native_depth_twoq_efficiency_details(circuit),
        )

        score = ArchitectureScore(
            architecture=architecture,
            expressibility=expressibility,
            trainability=trainability,
            noise_robustness=noise_robustness,
            hardware_efficiency=hardware_efficiency,
            weights=self.weights.to_dict(),
            weighted_score=0.0,
        )
        score.weighted_score = self.reward_composer.compose_architecture_score(score)
        return score

    def evaluate_many(self, architectures: Sequence[ArchitectureSpec]) -> List[ArchitectureScore]:
        return assign_ranks([self.evaluate(architecture) for architecture in architectures])


def evaluate_architectures(
    architectures: Sequence[ArchitectureSpec],
    backend: Optional[Backend] = None,
    noise_model: Optional[NoiseModel] = None,
    weights: Optional[RewardWeights] = None,
    n_samples: int = 200,
    active_metrics: Optional[Dict[str, str]] = None,
) -> List[ArchitectureScore]:
    evaluator = ArchitectureEvaluator(
        backend=backend,
        noise_model=noise_model,
        weights=weights,
        n_samples=n_samples,
        active_metrics=active_metrics,
    )
    return evaluator.evaluate_many(architectures)


try:
    from .qas_evaluation import EvaluationResult, QASEvaluator, noise_aware_reward, quick_evaluate
except ImportError:  # pragma: no cover - compatibility only
    EvaluationResult = QASEvaluator = quick_evaluate = noise_aware_reward = None  # type: ignore[assignment]


__all__ = [
    "ArchitectureEvaluator",
    "evaluate_architectures",
    "metric_catalog",
    "EvaluationResult",
    "QASEvaluator",
    "quick_evaluate",
    "noise_aware_reward",
]
